apiVersion: v1
kind: Service
metadata:
  name: super-important-app-service
  labels:
    app: super-important-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: super-important-app
